# CI/CD Workflow
#
# Runs on push and pull requests to main branch.
# Includes build, lint, test, and validation jobs.
#
# Customize based on your project structure.

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # ========================================
  # Job 1: Validate Configuration
  # ========================================
  validate-config:
    runs-on: ubuntu-latest
    name: Validate Config

    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON files
        run: |
          echo "Validating JSON files..."
          errors=0

          for json in $(find . -name "*.json" -not -path "./node_modules/*" -not -path "./.git/*"); do
            if python3 -c "import json; json.load(open('$json'))" 2>&1; then
              echo "  $json"
            else
              echo "  $json - INVALID"
              errors=$((errors + 1))
            fi
          done

          if [ $errors -gt 0 ]; then
            echo "Found $errors invalid JSON files"
            exit 1
          fi

      - name: Validate YAML files
        run: |
          echo "Validating YAML files..."

          for yaml in $(find . -name "*.yml" -o -name "*.yaml" | grep -v node_modules | grep -v .git); do
            if python3 -c "import yaml; yaml.safe_load(open('$yaml'))" 2>&1; then
              echo "  $yaml"
            else
              echo "  $yaml - INVALID"
              exit 1
            fi
          done

  # ========================================
  # Job 2: Build
  # ========================================
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Uncomment for pnpm
      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: 9

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          # Add any required build-time env vars
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 7

  # ========================================
  # Job 3: Lint
  # ========================================
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || true
        continue-on-error: true

      - name: Run Prettier check
        run: npm run format:check || true
        continue-on-error: true

  # ========================================
  # Job 4: Test
  # ========================================
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests configured"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/
          retention-days: 7

  # ========================================
  # Job 5: Security Audit
  # ========================================
  security:
    runs-on: ubuntu-latest
    name: Security Audit

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Audit dependencies
        run: npm audit --audit-level=high || true
        continue-on-error: true

  # ========================================
  # Job 6: Deploy (only on main)
  # ========================================
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [build, lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/

      - name: Deploy
        run: |
          echo "Deploying..."
          # Add your deployment commands here
          # Examples:
          # - wrangler pages deploy ./dist (Cloudflare)
          # - vercel --prod (Vercel)
          # - netlify deploy --prod (Netlify)
          echo "Deployment placeholder - customize for your platform"
