# Release Monitor Workflow
#
# Monitors a GitHub repository for new releases and sends notifications.
# Uses Claude API to generate summaries and feature highlights.
#
# Required Secrets:
# - ANTHROPIC_API_KEY: Claude API key
# - DISCORD_WEBHOOK_URL: Discord webhook (optional)
#
# Usage:
# 1. Copy to .github/workflows/release-monitor.yml
# 2. Update REPO_TO_MONITOR to your target repository
# 3. Add required secrets

name: Release Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Every hour

  workflow_dispatch:
    inputs:
      force_notify:
        description: 'Force notification even if no new release'
        required: false
        default: false
        type: boolean

env:
  # ========================================
  # CUSTOMIZE THESE VALUES
  # ========================================
  REPO_TO_MONITOR: anthropics/claude-code
  VERSION_FILE: .github/last-known-version.txt
  CLAUDE_MODEL: claude-sonnet-4-20250514

jobs:
  check-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_release: ${{ steps.check.outputs.new_release }}
      version: ${{ steps.check.outputs.version }}
      release_name: ${{ steps.check.outputs.release_name }}
      release_url: ${{ steps.check.outputs.release_url }}
      release_body: ${{ steps.check.outputs.release_body }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release
        id: fetch
        run: |
          echo "Fetching latest release from ${{ env.REPO_TO_MONITOR }}..."

          RELEASE_JSON=$(curl -s "https://api.github.com/repos/${{ env.REPO_TO_MONITOR }}/releases/latest")

          if echo "$RELEASE_JSON" | jq -e '.message' > /dev/null 2>&1; then
            echo "Error: $(echo "$RELEASE_JSON" | jq -r '.message')"
            exit 1
          fi

          VERSION=$(echo "$RELEASE_JSON" | jq -r '.tag_name')
          RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.name')
          RELEASE_URL=$(echo "$RELEASE_JSON" | jq -r '.html_url')
          RELEASE_BODY=$(echo "$RELEASE_JSON" | jq -r '.body // "No release notes"' | head -c 3000)

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT
          echo "$RELEASE_BODY" > /tmp/release_body.txt

          echo "Latest release: $VERSION"

      - name: Check if new release
        id: check
        run: |
          LATEST_VERSION="${{ steps.fetch.outputs.version }}"

          if [ -f "${{ env.VERSION_FILE }}" ]; then
            LAST_VERSION=$(cat "${{ env.VERSION_FILE }}")
          else
            LAST_VERSION="none"
          fi

          echo "Last known: $LAST_VERSION"
          echo "Latest: $LATEST_VERSION"

          if [ "$LATEST_VERSION" != "$LAST_VERSION" ] || [ "${{ github.event.inputs.force_notify }}" == "true" ]; then
            echo "new_release=true" >> $GITHUB_OUTPUT
            echo "New release detected!"
          else
            echo "new_release=false" >> $GITHUB_OUTPUT
            echo "No new release"
          fi

          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "release_name=${{ steps.fetch.outputs.release_name }}" >> $GITHUB_OUTPUT
          echo "release_url=${{ steps.fetch.outputs.release_url }}" >> $GITHUB_OUTPUT

          BODY_B64=$(base64 -w 0 /tmp/release_body.txt)
          echo "release_body=$BODY_B64" >> $GITHUB_OUTPUT

      - name: Update last known version
        if: steps.check.outputs.new_release == 'true'
        run: |
          mkdir -p $(dirname "${{ env.VERSION_FILE }}")
          echo "${{ steps.check.outputs.version }}" > "${{ env.VERSION_FILE }}"

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "${{ env.VERSION_FILE }}"
          git diff --staged --quiet || git commit -m "chore: update version to ${{ steps.check.outputs.version }}"
          git push || echo "Nothing to push"

  generate-content:
    needs: check-release
    runs-on: ubuntu-latest
    if: needs.check-release.outputs.new_release == 'true'
    outputs:
      summary: ${{ steps.generate.outputs.summary }}
      features: ${{ steps.generate.outputs.features }}

    steps:
      - name: Generate content with Claude API
        id: generate
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          VERSION: ${{ needs.check-release.outputs.version }}
          RELEASE_NAME: ${{ needs.check-release.outputs.release_name }}
          RELEASE_URL: ${{ needs.check-release.outputs.release_url }}
          RELEASE_BODY_B64: ${{ needs.check-release.outputs.release_body }}
        run: |
          RELEASE_BODY=$(echo "$RELEASE_BODY_B64" | base64 -d)

          PROMPT="You are a developer advocate. Summarize this release:
          Version: $VERSION
          Name: $RELEASE_NAME
          Notes: $RELEASE_BODY

          Return JSON only:
          {\"summary\": \"One sentence summary\", \"features\": \"• Feature 1\\n• Feature 2\"}"

          RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -d "{
              \"model\": \"${{ env.CLAUDE_MODEL }}\",
              \"max_tokens\": 1000,
              \"messages\": [{\"role\": \"user\", \"content\": $(echo "$PROMPT" | jq -Rs .)}]
            }")

          CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text')
          SUMMARY=$(echo "$CONTENT" | jq -r '.summary')
          FEATURES=$(echo "$CONTENT" | jq -r '.features')

          echo "summary=$(echo "$SUMMARY" | base64 -w 0)" >> $GITHUB_OUTPUT
          echo "features=$(echo "$FEATURES" | base64 -w 0)" >> $GITHUB_OUTPUT

  notify-discord:
    needs: [check-release, generate-content]
    runs-on: ubuntu-latest
    if: needs.check-release.outputs.new_release == 'true'

    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          VERSION: ${{ needs.check-release.outputs.version }}
          RELEASE_URL: ${{ needs.check-release.outputs.release_url }}
          SUMMARY_B64: ${{ needs.generate-content.outputs.summary }}
          FEATURES_B64: ${{ needs.generate-content.outputs.features }}
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "Discord webhook not configured, skipping"
            exit 0
          fi

          SUMMARY=$(echo "$SUMMARY_B64" | base64 -d)
          FEATURES=$(echo "$FEATURES_B64" | base64 -d)

          SUMMARY_ESCAPED=$(echo "$SUMMARY" | jq -Rs . | sed 's/^"//;s/"$//')
          FEATURES_ESCAPED=$(echo "$FEATURES" | jq -Rs . | sed 's/^"//;s/"$//')

          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{
              \"embeds\": [{
                \"title\": \"New Release: $VERSION\",
                \"description\": \"$SUMMARY_ESCAPED\",
                \"url\": \"$RELEASE_URL\",
                \"color\": 5763719,
                \"fields\": [
                  {\"name\": \"What's New\", \"value\": \"$FEATURES_ESCAPED\"},
                  {\"name\": \"Links\", \"value\": \"[View Release]($RELEASE_URL)\"}
                ],
                \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
              }]
            }"

  create-issue:
    needs: [check-release, generate-content]
    runs-on: ubuntu-latest
    if: needs.check-release.outputs.new_release == 'true'
    permissions:
      issues: write

    steps:
      - name: Create tracking issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.check-release.outputs.version }}
          RELEASE_URL: ${{ needs.check-release.outputs.release_url }}
          SUMMARY_B64: ${{ needs.generate-content.outputs.summary }}
        run: |
          SUMMARY=$(echo "$SUMMARY_B64" | base64 -d)

          gh issue create \
            --title "New release: $VERSION" \
            --body "## Summary
          $SUMMARY

          ## Links
          - [Release Notes]($RELEASE_URL)

          ## Tasks
          - [ ] Review changes
          - [ ] Update dependencies
          - [ ] Test compatibility" \
            --label "release-tracking"
