# Sync Upstream Repos Workflow
#
# Keeps git submodules updated with upstream repositories.
# Generates changelog and creates tracking issues.
#
# No secrets required (uses GITHUB_TOKEN).

name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get previous commits
        id: previous
        run: |
          echo "PREV_COMMITS<<EOF" >> $GITHUB_OUTPUT
          git submodule status >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update submodules
        run: |
          git submodule update --remote --merge

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate changelog
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          DATE=$(date +%Y-%m-%d)
          CHANGELOG_DIR=.github/upstream-changelog
          CHANGELOG_FILE="$CHANGELOG_DIR/${DATE}.md"

          mkdir -p $CHANGELOG_DIR

          echo "# Upstream Changes - ${DATE}" > $CHANGELOG_FILE
          echo "" >> $CHANGELOG_FILE
          echo "## Updated Repositories" >> $CHANGELOG_FILE
          echo "" >> $CHANGELOG_FILE

          # Check each submodule directory
          # Adjust this path based on your repo structure
          for repo in $(git submodule foreach --quiet 'echo $path'); do
            if [ -d "$repo" ]; then
              REPO_NAME=$(basename $repo)
              cd $repo

              # Get recent commits
              COMMITS=$(git log --oneline --since="7 days ago" 2>/dev/null | head -10)

              if [ -n "$COMMITS" ]; then
                echo "### $REPO_NAME" >> $GITHUB_WORKSPACE/$CHANGELOG_FILE
                echo '```' >> $GITHUB_WORKSPACE/$CHANGELOG_FILE
                echo "$COMMITS" >> $GITHUB_WORKSPACE/$CHANGELOG_FILE
                echo '```' >> $GITHUB_WORKSPACE/$CHANGELOG_FILE
                echo "" >> $GITHUB_WORKSPACE/$CHANGELOG_FILE
              fi

              cd $GITHUB_WORKSPACE
            fi
          done

          echo "---" >> $CHANGELOG_FILE
          echo "*Auto-generated by GitHub Actions*" >> $CHANGELOG_FILE

      - name: Commit and push
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "chore: sync upstream $(date +%Y-%m-%d)"
          git push

      - name: Create tracking issue
        if: steps.changes.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Upstream Update - ${date}`,
              body: `## Upstream repositories updated

            Check changelog at \`.github/upstream-changelog/${date}.md\`

            ### Action Items
            - [ ] Review changes
            - [ ] Update if breaking changes
            - [ ] Test compatibility
            - [ ] Update documentation`,
              labels: ['upstream-update', 'needs-review']
            });
